name: Analyze

on:
  push:
    paths:
      - "**.dart"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"

      - name: Analyze
        run: flutter analyze
