name: Build

on:
  push:
    paths:
      - "**.dart"
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web

      - name: Modify Base Tag
        run: sed -i 's/<base href="\/">/<base href="\/errorlookup\/html\/">/' build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-web
          path: build/web
