name: Coverage Report

on:
  workflow_run:
    workflows: [Unit Test]
    types:
      - completed

jobs:
  genhtml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup lcov
        run: sudo apt-get install -qqy lcov

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - name: Convert html
        run: genhtml artifact/lcov.info -o artifact/coverage

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact
