name: Unit Test

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"

      - name: Install Dependencies
        run: flutter pub get

      - name: Test
        run: flutter test --coverage

      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - name: Make Artifact
        run: |
          mkdir artifact
          mv build-web artifact/html
          mv coverage/lcov.info artifact/lcov.info

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact
